apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: sock-shop
  labels:

spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8079
  selector:
    name: front-end
  type: LoadBalancer
